# Generated by Django 3.1.7 on 2021-04-27 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationName', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('peopleCount', models.IntegerField()),
                ('boothTable', models.TextField()),
                ('requests', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
