# Generated by Django 3.1.7 on 2021-04-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantPizzaHut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleCount', models.TextField()),
                ('reservationName', models.TextField()),
            ],
        ),
    ]
