# Generated by Django 3.1.7 on 2021-04-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0002_restaurantpizzahut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurantPizzaHut',
            new_name='restaurantPizzaHutItem',
        ),
    ]
